public class ApexDataType 
{
    public static void Variables()
    {
        
        
        Date tday = Date.newInstance(1999, 04, 23);
        Time currentTime = Time.newInstance(07, 30, 00,00);
        DateTime cc = DateTime.newInstance(2020,04,24, 08, 30, 00);
        
        
        
        
        
        
        
        
        
       /* String greeting = 'Welcome to  Salesforce Class';
        system.debug('String = '+greeting);
        
        String Department = 'MCA';
        system.debug(department);
        
        Boolean ClassJoined = true;
        system.debug(ClassJoined);
        
        Integer Rollno = 101;
        system.debug(Rollno);
        
        Long Population = 15000000000L;
        System.debug(Population);
        
        Decimal Cgpa = 9.5;
        system.debug(cgpa);
        
        
        Double trainspeed = 564864651/654;
        system.debug(trainspeed);*/
        
               
        
        
    }
}