public class FunctionApex {

  /*  public static void greetings()
    {
         string Message = ' Good Morning!';
    	 system.debug(Message);
    }
    
    public static integer add(integer a, integer b)
    {
        
      	integer  sum = a + b;
      
        return sum;
        
    }
    
   // string Message = ' Good Morning!';
    system.debug(Message);*/
        
	public static string Month(string n)
    {
        return 'Month is '+ n ;
    }        
        
        
        
        
        
        
    
}