public class switchinApex 
{
		public static void statement()
        {
            
          /*  string n = 'sunday';
            
            switch on n
            {
             
                when 'Monday','Tuesday','Wednesday','Thursday','Friday'
                {
                    system.debug('Week Days...!!!');
                }
                when 'Saturday'
                {
                    System.debug('Week End ...Movie Tym');
                }
                when 'Sunday','sunday'
                {
                    System.debug('Fun day Sunday!');
                }
                when else
                {
                    System.debug('Invalid Day');
                }
                   
              
            }*/
            
            
            
            
            integer n = 6;
            switch on n
            {
                when  1,2,3,4,5,6,7,8,9,10,11
                {
                    system.debug('Good Morning Babe!');
                }
            }
            
            
            
            
            
            
            
            
        }
}