public class switchApex2
{
		public static void statement()
        {
            
         
            
            
            integer m = 24;
            switch on m
            {
                when  1,2,3,4,5,6,7,8,9,10,11
                {
                    system.debug('Good Morning Babe!');
                }
                when 12,13,14,15
                {
                    system.debug('Good Afternoon Ashi:>');
                }
                when 16,17,18,19,20
                {
                    system.debug('Good Evening Boys');
                }
                when 21,22,23,24
                {
                    system.debug('Good Night  Future! - Goibbo CTO Nithish Natrajan');
                }
                when else
                {
                    System.debug('Invalid Times to exit! 24hrs over');
                }
            }
    
        }
}